.TH ndsend 8 "1 May 2007" "OpenVZ" "Virtual Environments"
.SH NAME
ndsend \- helper program used by arpsend for IPv6.
.SH SYNOPSIS
ndsend \fBIPv6_ADDRESS\fR \fBNETWORK_INTERFACE\fR
.SH DESCRIPTION
The \fBndsend\fR utility is used by arpsend for IPv6 only.
It should only hooked by arpsend.
.SH OPTIONS
.TP
\fBIPv6_ADDRESS\fR
Specify the IPv6 address.
.TP
\fBNETWORK_INTERFACE\fR
Specify the network interface.
.SH SEE ALSO
.BR arpsend (8).
.SH LICENSE
Copyright (C) 2000-2007, SWsoft. Licensed under GNU GPL.
.SH "AUTHOR" 
.PP 
This manual page was written by Thorsten Schifferdecker <tsd@debian.systs.org> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).
